### ISSUE TITLE
doesn't seem to work with OS X El Capitan

### ISSUE THREAD

**Issue by wccalvin** [jiangmiao/auto-pairs#125]
#### I've cloned it to my ~/.vim/bundle/ and below is how my ~/.vimrc look.

```
" Settings related to pathogen
execute pathogen#infect()
syntax on
filetype on
filetype plugin on
filetype indent on

" Set Color Scheme
color Monokai

"---> Settings specific to python development <---

set number  " show line numbers
set ts=4  " set tabs to have 4 spaces

" expand tabs into spaces
set expandtab
set shiftwidth=4
set tabstop=4

set cursorline  " show a visual line under cursor's current line
set showmatch  " show the matching part of the pair for {} [] ()

let python_highlight_all = 1  " enable all python syntax highlighting features

" ---> End specific settings to python development <---

" ---> Some Basic Config <---

set encoding=utf-8
set nocompatible
set history=999
set autoindent 
set smartindent 
set wrap
set copyindent
set incsearch
set ignorecase
set smartcase
set autoread  " set to auto read when a file is changed from outside
set cmdheight=2  " height of the command bar
set ruler  " always show current position
set magic  " turn magic on for regular expressions
set hlsearch  " search highlighting
set laststatus=2  " always show the status line
set backspace=eol,start,indent

" ---> End Basic Config <---

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Copy to system clipboard
set clipboard+=unnamed
set paste

" Settings turned on for formating code every time a buffer is written
" rust.vim
let g:rustfmt_autosave = 1
```

**Comment by peidong** [comment]
@wccalvin For me, also OS X El Capitan, this plugin works. Have you overcome this problem?

**Comment by wccalvin** [comment]
I installed Mac vim to circumvent this issue.

**Comment by amandogra** [comment]
Try `:set nopaste` in the file or remove `set paste` from your `.vimrc` and see if it works.

**Comment by wccalvin** [comment]
@amandogra Thanks! that resolved it...

**Comment by jleclanche** [comment]
So how come `:set paste` causes that? Not setting that completely destroys indent when pasting from external sources in neovim, so unsetting it is not really an option =/

**Comment by galacticmonkeys** [comment]
I had the exact same issue, thank you!!!
@jleclanche I was looking for alternatives to `:set paste` and found this: https://coderwall.com/p/if9mda/automatically-set-paste-mode-in-vim-when-pasting-in-insert-mode
it might help!

**Comment by amandogra** [comment]
Hi @jleclanche you could either try what @galacticmonkeys suggested, but then each time you have to paste from external resources you have to press F2 function key
OR  You could do what I prefer. Instead of using the `Ctrl+V` or `Cmd+V`, use Vim's `p` command. You just have to read from `+` or `*` register while pasting from external source which we can achieve by using key combination `" + p` or `" * p`. This means that instead of pasting from the default register, I am pasting from the clipboard, which is usually stored in `+` or `*` registers. That way I never have to `:set paste`. Following VimCast tutorial covers this topic brilliantly http://vimcasts.org/episodes/accessing-the-system-clipboard-from-vim/

**Comment by galacticmonkeys** [comment]
@amandogra a little below the simple F2 mapping, they suggest a script that automatically sets and unsets the paste mode whenever you paste. But thanks for that link, I really like your tip! It's definitely faster than using ctrl + v in terminal vim for long blocks
