### ISSUE TITLE
No new line when writing braces

### ISSUE THREAD

**Issue by CodingJonas** [jiangmiao/auto-pairs#152]
I use the plugin under Ubuntu 16.04, with gVim.

It is working fine, except for one problem:

When I write 
`{`
it completes to
`{`
`|}`
instead of
`{`
`|`
`}`
and gVim gives me the error `unknown function BC_AddChar`

**Comment by optroot** [comment]
If you've followed [this guide (making parens) on vim wikia](http://vim.wikia.com/wiki/Making_Parenthesis_And_Brackets_Handling_Easier):

you should get rid of all those mappings.

I took a quick look at your vimrc, Go ahead and comment out line 250 and the functions at 256/264.

auto-pairs handles keypressing the `{` key, so anything else would be a conflict with unexpected results.

Check that the mapping is using auto-pairs with `:imap {` (and that there is no BC_AddChar map. Use `:iunmap {<CR>` to get rid of it if its still there. you might want to keep that in your vimrc for a while if you save views, or you should remove all views as it will be tainted with this mapping.

**Comment by CodingJonas** [comment]
Thank you for looking through my .vimrc, I removed all lines mapping the `{` key. 
The problem still exist, though now slightly different:

When I write 
`{`
it completes to
`{|}`
but when I hit `<CR>` it inserts two lines:
```
{
|
}
```
How can I set the plugin to automatically insert the new line when it inserts the closing brick?

**Comment by optroot** [comment]
This is the intended behavior, as sometimes you may want to inline {}, such as in javascript:

`myFunction({name:'hello'});`

or even just inline simple blocks

`if (a) { b; c; }`

I can definitely see how the behavior you describe is desirable, since the usages I describe are exceptions. A possible work around adding these to your vimrc

`iunmap <buffer> {`
`imap <buffer> <silent> { <C-R>=AutoPairsInsert('{')<CR><CR>`

**Comment by CodingJonas** [comment]
I am not a big fan of one-line blocks. So thanks for your help.

Unfortunately gVim reports this error when I start it with your addition:
```
Error detected while processing /home/jonas/.vimrc:
line   61:
E31: No such mapping
```
Removing `iunmap <buffer> {` does solve this error report, but the behavior stays as it was, with and without this line.

**Comment by optroot** [comment]
It seems like there is actually no clean way to do this without changing the source. Since the mappings are made on BufEnter...

I've gone ahead and added this feature to [my fork](https://github.com/optroot/auto-pairs), still awaiting merge here. (change 'jiangmiao/auto-pairs' to 'optroot/auto-pairs'). Hopefully my additions will get added soon.

then you can just add 

`let g:AutoPairsAutoNewlineAfter=['{']`

to your vimrc.

**Comment by CodingJonas** [comment]
Thank you, it works perfect!

**Comment by Herz3h** [comment]
Could this feature AutoNewLine option be added on the main project ?
