### ISSUE TITLE
Problem with Korean charactor input

### ISSUE THREAD

**Issue by 6qyzak** [jiangmiao/auto-pairs#176]
It works perfectly with English, Russian, etc. But it seems to have a problem with Korean.
Assume that I want to write '강' ('Kang' in English, which has two consonant while having one vowel(ㅏ) between them), to write so in Korean way, I type 'ㄱ', 'ㅏ', 'ㅇ' in following order. Without this powerful plugin 'auto-pairs' plugin, these characters combines perfectly and become '강'. But with 'auto-pairs' plugin enabled, the last character cannot be combined with preceding charactors (such as '가ㅇ'(Ka'ang), '다ㄹ'(Da'l)).
I understand that it's possible you're not familiar with Korean, but If it's fixed, I would appreciate your efforts.

**Comment by dqgthb** [comment]
I'm having the same problem with qyzanc. :(

**Comment by dqgthb** [comment]
I figured out that this can be fixed by modifying a few advanced settings in macvim. 
The solution is the following steps:
1. Ensure that you have something like
`set guifontwide=NanumGothic:h22`
inside your .vimrc.
2. Turn off `Use Core Text renderer` and `Draw marked text inline` options from MacVim preferences -> advanced.

**Comment by 6qyzak** [comment]
Thx for your reply, I'm not using macvim tho. But it would help others.
I actually solved this issue long times ago but I don't know why, so it'd be better close this issue : )
