### ISSUE TITLE
"Insert new indented line after Return" not working with completion-nvim

### ISSUE THREAD

**Issue by zd4y** [jiangmiao/auto-pairs#312]
Hello, with my current config, when I press enter here:
```
{|}
```
this is the result:
```
{
|}
```
instead of this:
```
{
    |
}
```
I am using the new lsp of neovim and the problem is fixed when I remove this line from my `lsp_config.lua`:
```lua
require'completion'.on_attach(client)
```
And this only happens when a lsp client is attached to the current buffer.
I saw the problem editing a javascript and a rust file
### My config:
`init.vim:`
```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
Plug 'jiangmiao/auto-pairs'

call plug#end()

lua require("lsp_config")

set expandtab
set shiftwidth=4
set tabstop=4
set smartindent

```
`lua/lsp_config.lua:`
```lua
local nvim_lsp = require('lspconfig')

local on_attach = function(client, bufnr)
  require'completion'.on_attach(client)
end

local servers = {
  "rust_analyzer",
  "pyright",
  "tsserver",
}

for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup { on_attach = on_attach }
end
```

**Comment by zd4y** [comment]
nvim version: `v0.5.0-dev+1013-gb535575ac`
I just updated the plugins with `PlugUpdate` so those should be the latest versions

**Comment by LunarWatcher** [comment]
What's the output of `:verbose imap <CR>`? Extremely sus completion-nvim remaps `<CR>` after autopairs, in which case you'll have to take it up with completion-nvim and tell them [to map CR in a compatible way](https://github.com/jiangmiao/auto-pairs/blob/master/plugin/auto-pairs.vim#L621-L664) (read: look for other `<CR>` maps and add them to the map when mapping `<CR>`). Autopairs can't fix it if other plugins remap `<CR>` later.

Mapping `<CR>` in general is tricky because it's a standard key, which makes it more prone to conflicts. ESPECIALLY enter when doing insert mappings, largely due to a combination of plugins hogging CR, and vim not supporting multiple unique keybinds per key. Alternatively, my fork has `g:AutoPairsCRKey` that lets you remap what key triggers the return action. [completion-nvim also has an option you can change](https://github.com/nvim-lua/completion-nvim/blob/master/plugin/completion.vim#L13), though that assumes you can live without `<CR>` to insert completions.

**Comment by zd4y** [comment]
Thanks for the reply @LunarWatcher, here is the output of `:verbose imap <CR>`:
```
i  <CR>         @pumvisible() ? complete_info()["selected"] != "-1" ? "\<Plug>(completion_confirm_completion)" : "\<C-E>\<CR>" : "\<CR>"
```
You are right, this seems to be a problem with completion-nvim rather than with auto-pairs. I was not sure on whether to post the issue here or in completion-nvim's repo and decided to do it here.

I will create the issue in the other repo later. If you want you can create it since you know better about this than me.

**Comment by saclman** [comment]
Hi, @zd4y 
Take a look at this [comment](https://github.com/nvim-lua/completion-nvim/issues/62#issuecomment-628764832). Hope this will help you cuz I had the same issue.

**Comment by zd4y** [comment]
Hey @tooSadman, thanks that works! And now that I see, it is also in the README. I don't know why I dind't search there first, sorry
